config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root 'application/home#index'
    namespace :admin do
        resources :home
        resources :stored_images
        resources :email_templates do
            collection do
                get 'default_email_template_source'
            end
        end
        resources :users do
            member do
                get 'edit_password'
                patch 'update_password'
            end
        end
    end
end

app/views/layouts/admin/_main_header.html.erb
<header id="main-header" class="clearfix">
    <ul>
        <li>
            <%= link_to admin_stored_images_path do %>
                <%= material_icon.perm_media %>
            <% end %>
        </li>
        <li>
            <%= link_to admin_email_templates_path do %>
                <%= material_icon.email %>
            <% end %>
        </li>
        <li>
            <%= link_to admin_users_path do %>
                <%= material_icon.people %>
            <% end %>
        </li>
    </ul>
</header>

app/views/layouts/admin/_page_header.html.erb
<header id="page-header" class="clearfix">
    <div class="page">
        <div class="container">
            <ul id="dropdown-current-user" class="dropdown pull-right">
                <button class="dropdown-toggle" data-toggle="dropdown">
                    <%= image_tag current_user.avatar(:small), onerror:"this.onerror=null;this.src='#{image_url('admin/no_avatar.png')}';" %>
                    <p><%= current_user.username %></p>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-header">
                        <%= image_tag current_user.avatar(:small), onerror:"this.onerror=null;this.src='#{image_url('admin/no_avatar.png')}';" %>
                        <h5><%= current_user.email %></h5>
                    </div>
                    <div class="dropdown-body">
                        <li><%= link_to t('edit_my_profile'), edit_admin_user_path(current_user) %></li>
                        <li><%= link_to t('change_my_password'), edit_password_admin_user_path(current_user) %></li>
                    </div>
                    <div class="dropdown-footer">
                        <%= link_to t('logout'), destroy_user_session_path, method: :delete, class: 'btn btn-blue btn-block' %>
                    </div>
                </div>
            </ul>
        </div>
    </div>
</header>