config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root 'application/home#index'
    namespace :admin do
        resources :home
        resources :stored_images
        resources :email_templates do
            collection do
                get 'default_email_template_source'
            end
        end
        resources :users do
            member do
                get 'edit_password'
                patch 'update_password'
            end
        end
    end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
    rolify
    devise :database_authenticatable,
           :registerable,
           :recoverable,
           :rememberable,
           :trackable,
           :validatable,
           authentication_keys: [:login]
    attr_accessor :login

    has_attached_file :avatar, styles: { small: '170x170', thumb: '50x50' }, default_url: '/assets/admin/no_avatar'
    validates_attachment_content_type :avatar, content_type: %r{/\Aimage\/.*\z/}
    validates :username, presence: :true, uniqueness: { case_sensitive: false }

    before_validation :set_username
    before_validation :user_default, on: :create

    def self.locales
        {
            en: {
                name: I18n.t('english')
            },
            fr: {
                name: I18n.t('french')
            }
        }
    end

    def self.find_first_by_auth_conditions(warden_conditions)
        conditions = warden_conditions.dup
        if login == conditions.delete(:login)
            where(conditions).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
        elsif conditions[:username].nil?
            where(conditions).first
        else
            where(username: conditions[:username]).first
        end
    end

    private

    def set_username
        self.username = email.split(/@/)[0]
    end

    def user_default
        add_role Role.find(1).name.to_sym
        self.locale = I18n.locale
    end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < AdminController
    before_action :set_admin_user, only: %i[show edit update destroy edit_password]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        respond_to do |format|
            generated_password = Devise.friendly_token.first(8)
            @user.password = generated_password
            @user.add_role params[:user][:roles]
            if @user.save
                UserMailer.welcome_email(@user, generated_password).deliver
                flash[:success] = I18n.t('successfully_created',
                                         title: @user.username,
                                         controller_name: I18n.t('user_controller'),
                                         flash_title: I18n.t('flash_title_created'))
                format.html { redirect_to admin_users_url }
            else
                flash[:error] = I18n.t('unsuccessfully_created',
                                       errors: @user.errors.messages[:name][0],
                                       flash_title: I18n.t('be_careful'))
                format.html { render :new }
            end
        end
    end

    def update
        respond_to do |format|
            @user.roles = []
            @user.add_role params[:user][:roles]
            if @user.update(user_params)
                flash[:success] = I18n.t('successfully_updated',
                                         title: @user.username,
                                         controller_name: I18n.t('user_controller'),
                                         flash_title: I18n.t('flash_title_updated'))
                format.html { redirect_to admin_users_url }
            else
                flash[:error] = []
                @user.errors.each do |attribute, error|
                    flash[:error] << I18n.t('unsuccessfully_updated',
                                            errors: error,
                                            flash_title: I18n.t(attribute))
                end
                format.html { render :edit }
            end
        end
    end

    def destroy
        respond_to do |format|
            if @user.destroy
                flash[:success] = I18n.t('successfully_destroyed',
                                         title: @user.username,
                                         controller_name: I18n.t('user_controller'),
                                         flash_title: I18n.t('flash_title_destroyed'))
                format.html { redirect_to admin_users_url }
            else
                format.html { render :index }
            end
        end
    end

    def update_password
        @user = current_user
        respond_to do |format|
            if @user.update(user_params)
                bypass_sign_in(@user)
                flash[:success] = I18n.t('successfully_updated',
                                         title: '',
                                         controller_name: I18n.t('your_password'),
                                         flash_title: I18n.t('flash_title_password'))
                format.html { redirect_to admin_home_index_url }
            else
                format.html { render :edit_password }
            end
        end
    end

    private

    def set_admin_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(
            :email,
            :username,
            :first_name,
            :last_name,
            :avatar,
            :phone,
            :locale
        )
    end
end

app/views/admin/users/_form.html.erb
<%= render 'admin/stored_images/index' %>
<div class="panel panel-default">
    <div class="panel-body">
        <%= form_for @user, url: {action: @user.new_record? ? 'create' : 'update'}, html: {class: 'form-primary form-validation', id: 'users-form'} do |f| %>
            <div class="row">
                <div class="user-avatar-container">
                    <div>
                        <%= image_tag @user.avatar(:small), onerror:"this.onerror=null;this.src='#{image_url('admin/no_avatar.png')}';" %>
                    </div>
                    <button type="button" data-toggle="modal" data-target="#modal-stored-images" data-turbolinks="false" }>
                        <%= material_icon.add %>
                    </button>
                </div>
                <div>
                    <h2><%= title %></h2>
                    <div class="row">
                        <div class="col-md-6">
                            <%= f.label :first_name %>
                            <%= f.text_field :first_name, class: 'form-control' %>
                        </div>
                        <div class="col-md-6">
                            <%= f.label :last_name %>
                            <%= f.text_field :last_name, class: 'form-control' %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <%= f.label :email, class: 'required' %>
                            <%= f.text_field :email, class: 'form-control', required: true %>
                        </div>
                        <div class="col-md-6">
                            <%= f.label :roles, class: 'required' %>
                            <%= f.select :roles, options_from_collection_for_select(Role.all, :name, :translated_name, (Role.find_by(name: @user.roles[0].name.to_s).name.to_s if @user.persisted?) ) , {}, class: 'form-control select2' %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <%= f.label :phone %>
                            <%= f.text_field :phone, class: 'form-control' %>
                        </div>
                        <div class="col-md-6">
                            <%= f.label :locale %>
                            <%= f.select :locale, User.locales.map{|key, value| [value[:name], key]}, {}, class: 'form-control select2' %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-footer pull-right">
                <%= link_to material_icon.arrow_back, admin_users_url, class: 'btn btn-grey', data: { turbolinks: false } %>
                <%= link_to material_icon.delete, admin_user_url(@user), class: 'btn btn-darkpurple', method: :delete, data: {confirm: t('confirm_destroy', title: @user.username, controller_name: t('user'))} if @user.persisted? && current_user != @user %>
                <%= f.submit class: 'btn btn-blue' %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
    <%= render 'form', title: t('edit_user', username: @user.username)  %>
</div>

app/views/admin/users/edit_password.html.erb
<div class="container">
    <%= render 'admin/stored_images/index' %>
    <div class="panel panel-default">
        <div class="panel-body">
            <%= form_for @user, url: {action: 'update_password'}, html: {class: 'form-primary form-validation'} do |f| %>
                <div>
                    <h2><%= t('edit_password') %></h2>
                    <div class="row">
                        <div class="col-md-6">
                            <%= f.label :password, class: 'required' %>
                            <%= f.password_field :password, class: 'form-control', autocomplete: 'off', required: true %>
                        </div>
                        <div class="col-md-6">
                            <%= f.label :password_confirmation, class: 'required' %>
                            <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off', required: true %>
                        </div>
                    </div>
                </div>
                <div class="form-footer pull-right">
                    <%= link_to material_icon.arrow_back, admin_users_path, class: 'btn btn-grey', data: { turbolinks: false } %>
                    <%= link_to material_icon.delete, @user, class: 'btn btn-darkpurple', method: :delete, data: {confirm: t('confirm_destroy', title: @user.username, controller_name: t('user'))} if @user.persisted? && current_user != @user %>
                    <%= f.submit class: 'btn btn-blue' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
    <table class="table-primary datatable">
        <%= link_to t('new_user'), new_admin_user_path, class: 'btn btn-darkpurple btn-new' %>
        <thead>
            <th><%= t 'username' %></th>
            <th><%= t 'name' %></th>
            <th><%= t 'email' %></th>
            <th><%= t 'roles' %></th>
            <th class="no-sorting" style="width:160px;"><%= t 'actions' %></th>
        </thead>
        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <td>
                        <div class="table-thumbnail">
                            <%= image_tag user.avatar(:thumb), onerror:"this.onerror=null;this.src='#{image_url('no-avatar.png')}';" %>
                            <span><%= user.username %></span>
                        </div>
                    </td>
                    <td>
                        <%= user.first_name %>
                        <%= user.last_name %>
                    </td>
                    <td>
                        <%= link_to user.email, "mailto: #{user.email}" %>
                    </td>
                    <td>
                        <% user.roles.each do |role| %>
                            <%= role.name.capitalize() %>
                        <% end %>
                    </td>
                    <td>
                        <div class="pull-right">
                            <%= link_to material_icon.mode_edit, edit_admin_user_path(user), class: 'btn btn-blue' %>
                            <%= link_to material_icon.delete, admin_user_url(user), class: 'btn btn-darkpurple', method: :delete, data: {confirm: t('confirm_destroy', title: user.username, controller_name: t('user'))} if current_user != user %>
                        </div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/users/new.html.erb
<div class="container">
    <%= render 'form', title: t('new_user')  %>
</div>